import turtle 
turtle.Screen().bgcolor("navy blue")
turtle.Screen().setup(400,400)
board=turtle.Turtle()
board.forward(100)
board.penup()
board.right(90)
board.pendown()
board.forward(100)
board.penup()
board.right(90)
board.pendown()
board.forward(100)
board.penup()
board.right(90)
board.pendown()
board.forward(100)  
board.penup()
board.right(90)
board.pendown()
turtle.done()